### PR TITLE
Add Azure global settings for queue creation

### PR DESCRIPTION
**Pull request by satabin**
When instantiating an Azure client, user may provide global settings (related to the namespace configuration in Azure) that will be used for every queue created with the client instance.

This comes in handy when working with partitioned namespaces, which require that every queue is partitioned in it.

### CODE REVIEW

**Comment by AL333Z** [comment]
- `NewQueueSettings` declaration is missing
- does it make sense to allow the override of certain properties (e.g. `queueSize`, `maxMessageSize`) in `ServiceBusAdministration.create`?

**Comment by satabin** [comment]
> * `NewQueueSettings` declaration is missing

🤦 

>     * does it make sense to allow the override of certain properties (e.g. `queueSize`, `maxMessageSize`) in `ServiceBusAdministration.create`?

The signature is common to all, and introducing a (type-safe) way to pass provider specific set of settings here will complicate the signature a lot. This is why I ruled it out so far.

**Comment by AL333Z** [comment]
> The signature is common to all, and introducing a (type-safe) way to pass provider specific set of settings here will complicate the signature a lot. This is why I ruled it out so far.

Fair enough. We can always add this later, if there is a need.

**Review by AL333Z — APPROVED** [review]
LGTM

**Pull request merged**
